<?php
return [
    'common'=>[
        'head'=>[
            'cp/plugins/fontawesome-free/css/all.min.css',
            'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css',
            'cp/dist/css/adminlte.min.css',
            'cp/dist/css/cp_my_custom.css',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',
        ],
        'foot'=>[
            'https://code.jquery.com/jquery-3.6.0.js',
            'cp/plugins/bootstrap/js/bootstrap.bundle.min.js',
            'cp/plugins/bs-custom-file-input/bs-custom-file-input.min.js',
            'cp/dist/js/adminlte.min.js'
            ]
    ],
    'datatables'=>[
        'head'=>[
            'cp/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css',
            'cp/plugins/datatables-responsive/css/responsive.bootstrap4.min.css',
            'cp/plugins/datatables-buttons/css/buttons.bootstrap4.min.css',
        
        ],
        'foot'=>[
            'cp/plugins/datatables/jquery.dataTables.min.js',
            'cp/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js',
            'cp/plugins/datatables-responsive/js/dataTables.responsive.min.js',
            'cp/plugins/datatables-responsive/js/responsive.bootstrap4.min.js',
            'cp/plugins/datatables-buttons/js/dataTables.buttons.min.js',
            'cp/plugins/datatables-buttons/js/buttons.bootstrap4.min.js',
            'cp/plugins/jszip/jszip.min.js',
            'cp/plugins/pdfmake/pdfmake.min.js',
            'cp/plugins/pdfmake/vfs_fonts.js',
            'cp/plugins/datatables-buttons/js/buttons.html5.min.js',
            'cp/plugins/datatables-buttons/js/buttons.print.min.js',
            'cp/plugins/datatables-buttons/js/buttons.colVis.min.js'
        ]
    ],
    'select2'=>[
        'head'=>[
            'https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.min.css',
            'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css'
        ],
        'foot'=>[
           'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js'
        ]
    ]
];